<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxo2vyq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxo2vyq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAxo2vyq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAxo2vyq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAxo2vyq\appProdProjectContainer([
    'container.build_hash' => 'Axo2vyq',
    'container.build_id' => 'fe171b5c',
    'container.build_time' => 1699324390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxo2vyq');
