<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5bxwimp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5bxwimp/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5bxwimp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5bxwimp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5bxwimp\appProdProjectContainer([
    'container.build_hash' => '5bxwimp',
    'container.build_id' => '01b5d3d6',
    'container.build_time' => 1699366147,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5bxwimp');
